### ISSUE TITLE
Datasources.txt, issues loading latest data

### ISSUE THREAD

**Issue by nunogit** [bridgedb/BridgeDb#112]
@marvinm2 your last update to the datasources.txt file is creating some issues.
It seems to me to be related to the number of fields you added.
Can you check, please?

**Comment by marvinm2** [comment]
https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.bio/resources/org/bridgedb/bio/datasources.txt

Should be fine now! It had spaces instead of tabs, my mistake with pasting

**Comment by egonw** [comment]
@marvinm2, please run the test suite before you make a pull request ;)

**Comment by marvinm2** [comment]
I didn't know about that, it is why I asked for a review before the merge. I hope it is solved now anyway.

**Comment by egonw** [comment]
@marvinm2, next time, please give precise instructions of what you expect. For clarity, no worries, these things happen. 

BTW, I think I've isolated what went wrong. I do normally compile things, and in the past I learned that Maven doesn't install a bundle if it has test fails. But that never was or no longer is the situation, and since things installed, I assumed the test suite ran fine. It didn't.

**Comment by egonw** [comment]
@marvinm2, please see the README for explanation on how to run the unit tests.

You almost fixed the problems :)
