### ISSUE TITLE
set up advisory board

### ISSUE THREAD

**Issue by egonw** [bridgedb/BridgeDb#80]
We need to set up a SAB and I want to invite people before the x-mas holidays. Step 1 is to define a list of 5 people we wish to have on your board. Please add names and reasons for candidates:

- Nick Juty (for identifiers.org)
- someone from Ensembl (major mapping provider)
- Gert or Diego from the UCDavid metabolomics map (host of the Chemical Translation Service)
- Alex (representing WikiPathways, major BridgeDb user)

**Comment by Chris-Evelo** [comment]
The plan so far was to use the advisory board from DTL/ELIXIR-NL and extend that for specific services with one or two people with relevant expertise. Some of the people you mention would possibly fit to that last group. SAB members are typically people that understand the service and have a good overview of the whole field (in this case also the alternatives, and the research use cases).

Since you typically have to fly such people in on a regular basis.it is pragmatic for a smaller project like BridgeDb to limit the number of people from the US.

I don't think Alex is a good fit since he is too close. Most people working on BridgeDb in fact know about WikiPathways needs best

**Comment by egonw** [comment]
Awaiting outcome of rebuttal.

**Comment by Chris-Evelo** [comment]
Will be discussed at Heads of Nodes meeting in Brussels next week. I cannot participate and Jaap cannot be present. So it will take one or few weeks after that before we get an update

**Comment by egonw** [comment]
@Chris-Evelo, any update on this?

**Comment by Chris-Evelo** [comment]
Nope. Too busy mainly. Just asked Rob whether it was discussed at the node services evaluation by the ELIXIR SAB recently. As far as we want suggestions for our own SAB we should probably discuss that in the next BridgeDb telco. Has that been set?
